#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @PypiSeedTag: MainTest
# @Project : text-to-gif

import os
import unittest

import text_to_gif.env_options as env

"""
generated by PypiSeed(PPC) - EnvOptions Unittest
"""


class EnvOptionsTestCase(unittest.TestCase):
    def test_get_value(self):
        actual = env.get_value('A_KEY_NOT_EXIST', False)
        expect = False
        self.assertEqual(expect, actual, "Must match")

    def test_do_ssl_check(self):
        actual = env.do_ssl_check()
        expect = False
        self.assertEqual(expect, actual, "Must match")

    def test_skip_user_doc_load(self):
        actual = env.skip_user_doc_load()
        expect = False
        self.assertEqual(expect, actual, "Must match")


if __name__ == '__main__':
    unittest.main()
