#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @PypiSeedTag: MainTest
# @Project : text-to-gif

import os
import unittest

import text_to_gif.main as main

"""
generated by PypiSeed(PPC) - Unittest
"""


class MainTestCase(unittest.TestCase):
    def test_main(self):
        has_error = False
        expect = False
        self.assertEqual(expect, has_error, "Must match")


if __name__ == '__main__':
    unittest.main()
