#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @PypiSeedTag: MainTest
# @Project : text-to-gif

import os
import unittest

import text-to-gif.main as main


"""
generated by PypiSeed(PPC) - Unittest
"""

class MainTestCase(unittest.TestCase):
    def test_main(self):
        actual = main.main()
        expect = "hello text-to-gif"
        self.assertEqual(expect, actual, "Must match")


if __name__ == '__main__':
    unittest.main()
